### ISSUE TITLE
Strange behaviour this plugin vs plugin available in moodle 3.7.1

### ISSUE THREAD

**Issue by soda31** [learnweb/moodle-repository_owncloud#44]
Hello,

I use moodle 3.7.1 and last version of nextcloud.
I configured oAuth2, and all required parameters to use nextcloud in moodle
I want to link to nextcloud files and do not want to have them inside moodle.

Unable to get it with nextcloud plugin embedded in moodle

I tryed moodle demo site with nextcloud demo site to be sure that the problem was not from my platform

Strange thing :
with moodle nexcloud plugin I do not have the option to use link to nexcloud file
I have "create a file copy"
![moodle-nextcloud-link_KO](https://user-images.githubusercontent.com/53428797/62040973-e7c68c00-b1fa-11e9-8f4d-64dc3f2e8e57.png)

With this plugin I have the option and all is working fine
(create a file alias == link)

![moodle-nextcloud-link_OK](https://user-images.githubusercontent.com/53428797/62040544-1ee86d80-b1fa-11e9-8db1-ce70ccdbf5a9.png)

The link option (alias in screenshot) is not avaialble in nextcloud moodle plugin ?!!

I set parameters for boths in the same way

Any idea ?

Thanks !

**Comment by Dagefoerde** [comment]
Yes, the Alias option is not available in the official Moodle plugin. If you are missing the feature, note that this is not the correct place to report it, as it would need to be fixed in Moodle and not in this plugin. After all, this option exists in this plugin. The correct place would be https://tracker.moodle.org.

Nevertheless, please consider using the official plugin, mainly for two reasons. First, this plugin is not under active development (in contrast to the official Moodle plugin). Second, you aim to provide files without copying them into Moodle - the official plugin supports that, just not via the Alias option. Use the "access controlled link" option instead. The files will remain in Nextcloud.

**Comment by soda31** [comment]
Hello,

Thanks for your quick answer
I'm going to post a message on https://tracker.moodle.org.

Problem is that  "access controlled link" does not work for me , that's why I tryed this plugin 

I have following error
 Debug info:
Error code: cannotdownload
Stack trace:

    line 386 of /repository/nextcloud/lib.php: repository_exception thrown
    line 1223 of /lib/filelib.php: call to repository_nextcloud->reference_file_selected()
    line 535 of /mod/resource/locallib.php: call to file_save_draft_area_files()
    line 107 of /mod/resource/lib.php: call to resource_set_mainfile()
    line 122 of /course/modlib.php: call to resource_add_instance()
    line 154 of /course/modedit.php: call to add_moduleinfo()


I tryed native nextcloud plugin with demo moodle website, same error

I post a message in moodle community forum
https://moodle.org/mod/forum/discuss.php?d=388906

Don't know where problem is !

Do you have some hints ?
